language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
    - WP_VERSION=4.1-RC3 WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
